version: "3"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: unless-stopped
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    image: 'bitnami/kafka:latest'
    restart: unless-stopped
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_ADVERTISED_HOST_NAME: 'kafka'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --list  --bootstrap-server kafka:9092" ]
      interval: 55s
      timeout: 50s
      retries: 10

  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb/entrypoint-initdb.d:/docker-entrypoint-initdb.d

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3
      - DEBUG=0
      - AWS_DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - USE_SSL=false
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
      - ./aws/index.html:/root/index.html
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"