version: "3"

services:
  dp-files-api:
    image: template_test
    ports:
      - "26900:26900"
    environment:
      BIND_ADDR: ':'
      GRACEFUL_SHUTDOWN_TIMEOUT: '30s'
      HEALTHCHECK_INTERVAL: '5s'
      HEALTHCHECK_CRITICAL_TIMEOUT: '30s'
      MONGODB_USERNAME: 'tester'
      MONGODB_PASSWORD: 'testing'
      MONGODB_BIND_ADDR: 'mongo'
      MONGODB_DATABASE: 'files'
      MONGODB_IS_SSL: 'false'
      MONGODB_ENABLE_READ_CONCERN: 'false'
      MONGODB_ENABLE_WRITE_CONCERN: 'true'
      MONGODB_CONNECT_TIMEOUT: '30s'
      MONGODB_QUERY_TIMEOUT: '5s'

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: unless-stopped
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    image: 'bitnami/kafka:latest'
    restart: unless-stopped
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_ADVERTISED_HOST_NAME: 'kafka'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    depends_on:
      - zookeeper

  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb/entrypoint-initdb.d:/docker-entrypoint-initdb.d