version: "3.3"

services:
  dp-files-api:
    image: template_test
    ports:
      - "26900:26900"
    environment:
      BIND_ADDR: ':'
      GRACEFUL_SHUTDOWN_TIMEOUT: '30s'
      HEALTHCHECK_INTERVAL: '5s'
      HEALTHCHECK_CRITICAL_TIMEOUT: '30s'
      AUTHORISATION_ENABLED: 'false'
      MONGODB_USERNAME: 'tester'
      MONGODB_PASSWORD: 'testing'
      MONGODB_BIND_ADDR: 'mongo'
      MONGODB_DATABASE: 'files'
      MONGODB_IS_SSL: 'false'
      MONGODB_ENABLE_READ_CONCERN: 'false'
      MONGODB_ENABLE_WRITE_CONCERN: 'true'
      MONGODB_CONNECT_TIMEOUT: '30s'
      MONGODB_QUERY_TIMEOUT: '5s'
    depends_on:
      kafka:
        condition: service_healthy
