swagger: "2.0"
info:
  title: "dp-files-api"
  description: "Digital Publishing API for handling file metadata"
  version: 1.0.0
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"

schemes:
  - http

basePath: http://localhost:26900/

tags:
  - name: "private"

paths:
  /v1/files/register:
    post:
      tags:
        - File upload started
      summary: POST's metadata for a file when an upload has started
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/new_file_upload'
      responses:
        201:
          description: OK
        400:
          $ref: '#/responses/JsonErrors'
        500:
          $ref: '#/responses/InternalError'

  /v1/files/upload-complete:
    post:
      tags:
        - File upload complete
      summary: POST's metadata for a file when an upload has completed
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/file_upload_complete'
      responses:
        201:
          description: OK
        400:
          $ref: '#/responses/JsonErrors'
        500:
          $ref: '#/responses/InternalError'

  /v1/files/{filepath}:
    get:
      tags:
        - Fetch file metadata
      summary: GET the metadata for a file whose upload has started
      produces:
        - application/json
      parameters:
        - name: filepath
          in: path
          required: true
          description: filepath of required file
      responses:
        200:
          schema:
            $ref: '#/definitions/metadata'
        404:
          $ref: '#/responses/JsonErrors'
        500:
          $ref: '#/responses/InternalError'

  /health:
    get:
      tags:
        - private
      summary: "Returns API's health status"
      description: "Returns health status of the API and checks on dependent services"
      produces:
        - application/json
      responses:
        200:
          description: "Successfully returns OK status with checks of dependent services"
          schema:
            $ref: "#/definitions/Health"
        429:
          description: "Services warming up or degraded (at least one health in WARNING or CRITICAL status)"
        500:
          $ref: "#/responses/InternalError"

responses:
  InternalError:
    description: "Failed to process the request due to an internal error"
  JsonErrors:
    type: object
    description: "Common error response format"
    schema:
      $ref: "#/definitions/Error"

definitions:
  RegisterFileUploadResponse:
    type: object
    properties:
      message:
        type: string
        description: "Message returned by hello world endpoint"
        example: "Hello, world!"
  Health:
    type: object
    properties:
      status:
        type: string
        description: "The status of the API"
        enum: ["OK", "WARNING", "CRITICAL"]
      version:
        type: object
        properties:
          build_time:
            type: string
            description: "The build date and time of the API"
            example: "2020-06-11T12:49:20+01:00"
          git_commit:
            type: string
            description: "The git commit hash of the API"
            example: "7c2febbf2b818175112478d4ffbadbee1b654f63"
          language:
            type: string
            description: "The programming language used to implement API"
            example: "go"
          language_version:
            type: string
            description: "The version of the programming language used to implement API"
            example: "go1.14.3"
          version:
            type: string
            description: "The version of API"
            example: "1.0.0"
      uptime:
        type: string
        description: "The uptime of API"
        example: "34516"
      start_time:
        type: string
        description: "The start date and time of API running"
        example: "2020-06-11T11:49:21.520922Z"
      checks:
        type: array
        items:
          $ref: '#/definitions/HealthChecker'
  HealthChecker:
    type: object
    properties:
      name:
        type: string
        description: "The name of external service used by API"
        enum: ["mongodb"]
      status:
        type: string
        description: "The status of the external service"
        enum: ["OK", "WARNING", "CRITICAL"]
      message:
        type: string
        description: "The message status of the external service"
        example: "mongodb is OK"
      last_checked:
        type: string
        description: "The last health health date and time of the external service"
        example: "2020-06-11T11:49:50.330089Z"
      last_success:
        type: string
        description: "The last successful health health date and time of the external service"
        example: "2020-06-11T11:49:50.330089Z"
      last_failure:
        type: string
        description: "The last failed health health date and time of the external service"
        example: "2019-09-22T11:48:51.0000001Z"
  NewFileUpload:
    type: object
    description: "New file upload metadata to be POSTed"
    required:
      - "path"
      - "is_publishable"
      - "collection_id"
      - "size_in_bytes"
      - "type"
      - "licence"
      - "licence_url"
    properties:
      path:
        type: string
        description: "Path to file"
        example: "images/meme.jpg"
      is_publishable:
        type: boolean
        description: "Is the file publishable"
        example: true
      collection_id:
        type: string
        description: "The collection ID to which the file is attached"
        example: "1234-asdfg-54321-qwerty"
      title:
        type: string
        description: "The title given to the file"
        example: "The latest Meme"
      size_in_bytes:
        type: integer
        description: "Size of the file in bytes"
        example: 14794
      type:
        type: string
        description: "The file type"
        example: "image/jpeg"
      licence:
        type: string
        description: "The type of licence the file has"
        example: "OGL v3"
      licence_url:
        type: string
        description: "Licence URL"
        example: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
  FileUploadComplete:
    type: object
    description: "File upload complete metadata to be POSTed"
    required:
      - "path"
      - "etag"
    properties:
      path:
        type: string
        description: "Path to file"
        example: "images/meme.jpg"
      etag:
        type: string
        description: "The etag for the file"
        example: "194577a7e20bdcc7afbb718f502c134c"
  metadata:
    type: object
    description: "File metadata"
    properties:
      path:
        type: string
        description: "Path to file"
        example: "images/meme.jpg"
      is_publishable:
        type: boolean
        description: "Is the file publishable"
        example: true
      collection_id:
        type: string
        description: "The collection ID to which the file is attached"
        example: "1234-asdfg-54321-qwerty"
      title:
        type: string
        description: "The title given to the file"
        example: "The latest Meme"
      size_in_bytes:
        type: integer
        description: "Size of the file in bytes"
        example: 14794
      type:
        type: string
        description: "The file type"
        example: "image/jpeg"
      licence:
        type: string
        description: "The type of licence the file has"
        example: "OGL v3"
      licence_url:
        type: string
        description: "Licence URL"
        example: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
      etag:
        type: string
        description: "File etag"
        example: "1234567890asdfghjk"
      status:
        type: string
        description: "File status"
        example: "UPLOADED"
  Error:
    type: object
    properties:
      errors:
        type: array
        items:
          type: object
          properties:
            code:
              type: string
              example: BadJson
            description:
              type: string
              example: The JSON is not in a valid format

parameters:
  new_file_upload:
    name: new_file_upload
    description: "Register a new file upload"
    in: body
    required: true
    schema:
      $ref: '#/definitions/NewFileUpload'

  file_upload_complete:
    name: new_file_upload
    description: "Register that a file upload has completed"
    in: body
    required: true
    schema:
      $ref: '#/definitions/FileUploadComplete'