// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/ONSdigital/dp-api-clients-go/v2/health"
	"github.com/ONSdigital/dp-files-api/files"
	"github.com/ONSdigital/dp-files-api/sdk"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"sync"
)

// Ensure, that ClienterMock does implement sdk.Clienter.
// If this is not the case, regenerate this file with moq.
var _ sdk.Clienter = &ClienterMock{}

// ClienterMock is a mock implementation of sdk.Clienter.
//
//	func TestSomethingThatUsesClienter(t *testing.T) {
//
//		// make and configure a mocked sdk.Clienter
//		mockedClienter := &ClienterMock{
//			CheckerFunc: func(ctx context.Context, check *healthcheck.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			CreateFileEventFunc: func(ctx context.Context, event files.FileEvent, headers sdk.Headers) (*files.FileEvent, error) {
//				panic("mock out the CreateFileEvent method")
//			},
//			DeleteFileFunc: func(ctx context.Context, filePath string, headers sdk.Headers) error {
//				panic("mock out the DeleteFile method")
//			},
//			GetFileFunc: func(ctx context.Context, filePath string, headers sdk.Headers) (*files.StoredRegisteredMetaData, error) {
//				panic("mock out the GetFile method")
//			},
//			HealthFunc: func() *health.Client {
//				panic("mock out the Health method")
//			},
//			MarkFilePublishedFunc: func(ctx context.Context, filePath string, headers sdk.Headers) error {
//				panic("mock out the MarkFilePublished method")
//			},
//			URLFunc: func() string {
//				panic("mock out the URL method")
//			},
//		}
//
//		// use mockedClienter in code that requires sdk.Clienter
//		// and then make assertions.
//
//	}
type ClienterMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, check *healthcheck.CheckState) error

	// CreateFileEventFunc mocks the CreateFileEvent method.
	CreateFileEventFunc func(ctx context.Context, event files.FileEvent, headers sdk.Headers) (*files.FileEvent, error)

	// DeleteFileFunc mocks the DeleteFile method.
	DeleteFileFunc func(ctx context.Context, filePath string, headers sdk.Headers) error

	// GetFileFunc mocks the GetFile method.
	GetFileFunc func(ctx context.Context, filePath string, headers sdk.Headers) (*files.StoredRegisteredMetaData, error)

	// HealthFunc mocks the Health method.
	HealthFunc func() *health.Client

	// MarkFilePublishedFunc mocks the MarkFilePublished method.
	MarkFilePublishedFunc func(ctx context.Context, filePath string, headers sdk.Headers) error

	// URLFunc mocks the URL method.
	URLFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Check is the check argument value.
			Check *healthcheck.CheckState
		}
		// CreateFileEvent holds details about calls to the CreateFileEvent method.
		CreateFileEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event files.FileEvent
			// Headers is the headers argument value.
			Headers sdk.Headers
		}
		// DeleteFile holds details about calls to the DeleteFile method.
		DeleteFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
			// Headers is the headers argument value.
			Headers sdk.Headers
		}
		// GetFile holds details about calls to the GetFile method.
		GetFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
			// Headers is the headers argument value.
			Headers sdk.Headers
		}
		// Health holds details about calls to the Health method.
		Health []struct {
		}
		// MarkFilePublished holds details about calls to the MarkFilePublished method.
		MarkFilePublished []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
			// Headers is the headers argument value.
			Headers sdk.Headers
		}
		// URL holds details about calls to the URL method.
		URL []struct {
		}
	}
	lockChecker           sync.RWMutex
	lockCreateFileEvent   sync.RWMutex
	lockDeleteFile        sync.RWMutex
	lockGetFile           sync.RWMutex
	lockHealth            sync.RWMutex
	lockMarkFilePublished sync.RWMutex
	lockURL               sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *ClienterMock) Checker(ctx context.Context, check *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("ClienterMock.CheckerFunc: method is nil but Clienter.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Check *healthcheck.CheckState
	}{
		Ctx:   ctx,
		Check: check,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, check)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedClienter.CheckerCalls())
func (mock *ClienterMock) CheckerCalls() []struct {
	Ctx   context.Context
	Check *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		Check *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// CreateFileEvent calls CreateFileEventFunc.
func (mock *ClienterMock) CreateFileEvent(ctx context.Context, event files.FileEvent, headers sdk.Headers) (*files.FileEvent, error) {
	if mock.CreateFileEventFunc == nil {
		panic("ClienterMock.CreateFileEventFunc: method is nil but Clienter.CreateFileEvent was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Event   files.FileEvent
		Headers sdk.Headers
	}{
		Ctx:     ctx,
		Event:   event,
		Headers: headers,
	}
	mock.lockCreateFileEvent.Lock()
	mock.calls.CreateFileEvent = append(mock.calls.CreateFileEvent, callInfo)
	mock.lockCreateFileEvent.Unlock()
	return mock.CreateFileEventFunc(ctx, event, headers)
}

// CreateFileEventCalls gets all the calls that were made to CreateFileEvent.
// Check the length with:
//
//	len(mockedClienter.CreateFileEventCalls())
func (mock *ClienterMock) CreateFileEventCalls() []struct {
	Ctx     context.Context
	Event   files.FileEvent
	Headers sdk.Headers
} {
	var calls []struct {
		Ctx     context.Context
		Event   files.FileEvent
		Headers sdk.Headers
	}
	mock.lockCreateFileEvent.RLock()
	calls = mock.calls.CreateFileEvent
	mock.lockCreateFileEvent.RUnlock()
	return calls
}

// DeleteFile calls DeleteFileFunc.
func (mock *ClienterMock) DeleteFile(ctx context.Context, filePath string, headers sdk.Headers) error {
	if mock.DeleteFileFunc == nil {
		panic("ClienterMock.DeleteFileFunc: method is nil but Clienter.DeleteFile was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FilePath string
		Headers  sdk.Headers
	}{
		Ctx:      ctx,
		FilePath: filePath,
		Headers:  headers,
	}
	mock.lockDeleteFile.Lock()
	mock.calls.DeleteFile = append(mock.calls.DeleteFile, callInfo)
	mock.lockDeleteFile.Unlock()
	return mock.DeleteFileFunc(ctx, filePath, headers)
}

// DeleteFileCalls gets all the calls that were made to DeleteFile.
// Check the length with:
//
//	len(mockedClienter.DeleteFileCalls())
func (mock *ClienterMock) DeleteFileCalls() []struct {
	Ctx      context.Context
	FilePath string
	Headers  sdk.Headers
} {
	var calls []struct {
		Ctx      context.Context
		FilePath string
		Headers  sdk.Headers
	}
	mock.lockDeleteFile.RLock()
	calls = mock.calls.DeleteFile
	mock.lockDeleteFile.RUnlock()
	return calls
}

// GetFile calls GetFileFunc.
func (mock *ClienterMock) GetFile(ctx context.Context, filePath string, headers sdk.Headers) (*files.StoredRegisteredMetaData, error) {
	if mock.GetFileFunc == nil {
		panic("ClienterMock.GetFileFunc: method is nil but Clienter.GetFile was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FilePath string
		Headers  sdk.Headers
	}{
		Ctx:      ctx,
		FilePath: filePath,
		Headers:  headers,
	}
	mock.lockGetFile.Lock()
	mock.calls.GetFile = append(mock.calls.GetFile, callInfo)
	mock.lockGetFile.Unlock()
	return mock.GetFileFunc(ctx, filePath, headers)
}

// GetFileCalls gets all the calls that were made to GetFile.
// Check the length with:
//
//	len(mockedClienter.GetFileCalls())
func (mock *ClienterMock) GetFileCalls() []struct {
	Ctx      context.Context
	FilePath string
	Headers  sdk.Headers
} {
	var calls []struct {
		Ctx      context.Context
		FilePath string
		Headers  sdk.Headers
	}
	mock.lockGetFile.RLock()
	calls = mock.calls.GetFile
	mock.lockGetFile.RUnlock()
	return calls
}

// Health calls HealthFunc.
func (mock *ClienterMock) Health() *health.Client {
	if mock.HealthFunc == nil {
		panic("ClienterMock.HealthFunc: method is nil but Clienter.Health was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHealth.Lock()
	mock.calls.Health = append(mock.calls.Health, callInfo)
	mock.lockHealth.Unlock()
	return mock.HealthFunc()
}

// HealthCalls gets all the calls that were made to Health.
// Check the length with:
//
//	len(mockedClienter.HealthCalls())
func (mock *ClienterMock) HealthCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHealth.RLock()
	calls = mock.calls.Health
	mock.lockHealth.RUnlock()
	return calls
}

// MarkFilePublished calls MarkFilePublishedFunc.
func (mock *ClienterMock) MarkFilePublished(ctx context.Context, filePath string, headers sdk.Headers) error {
	if mock.MarkFilePublishedFunc == nil {
		panic("ClienterMock.MarkFilePublishedFunc: method is nil but Clienter.MarkFilePublished was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FilePath string
		Headers  sdk.Headers
	}{
		Ctx:      ctx,
		FilePath: filePath,
		Headers:  headers,
	}
	mock.lockMarkFilePublished.Lock()
	mock.calls.MarkFilePublished = append(mock.calls.MarkFilePublished, callInfo)
	mock.lockMarkFilePublished.Unlock()
	return mock.MarkFilePublishedFunc(ctx, filePath, headers)
}

// MarkFilePublishedCalls gets all the calls that were made to MarkFilePublished.
// Check the length with:
//
//	len(mockedClienter.MarkFilePublishedCalls())
func (mock *ClienterMock) MarkFilePublishedCalls() []struct {
	Ctx      context.Context
	FilePath string
	Headers  sdk.Headers
} {
	var calls []struct {
		Ctx      context.Context
		FilePath string
		Headers  sdk.Headers
	}
	mock.lockMarkFilePublished.RLock()
	calls = mock.calls.MarkFilePublished
	mock.lockMarkFilePublished.RUnlock()
	return calls
}

// URL calls URLFunc.
func (mock *ClienterMock) URL() string {
	if mock.URLFunc == nil {
		panic("ClienterMock.URLFunc: method is nil but Clienter.URL was just called")
	}
	callInfo := struct {
	}{}
	mock.lockURL.Lock()
	mock.calls.URL = append(mock.calls.URL, callInfo)
	mock.lockURL.Unlock()
	return mock.URLFunc()
}

// URLCalls gets all the calls that were made to URL.
// Check the length with:
//
//	len(mockedClienter.URLCalls())
func (mock *ClienterMock) URLCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockURL.RLock()
	calls = mock.calls.URL
	mock.lockURL.RUnlock()
	return calls
}
